// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwjwxlvbhnewfwfoqhtx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3and4bHZiaG5ld2Z3Zm9xaHR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU2MzcwNzgsImV4cCI6MjA1MTIxMzA3OH0.2ZWkagyCVpfksOAN8VQR-9It2Xqvjoo81iMTkpQu2BE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);